#yaml配置注入
person:
 age: 20
 name: 张三
 happy: false
 birth: 2001//11//02
 map: {k1: v1,k2: v2}
 list:
    - code
    - music
    - gile
 dog:
  name: 旺财
  age: 8
#spring boot 的多环境配置
#spring:
# profiles:
#  active: dev
server:
  port: 8080
---

sever:
 port: 8081
spring:
 profiles: dev
---
spring:
  profiles: test
sever:
  port: 8082
